### ISSUE TITLE
Texture Specialization (Texture1D, Texture2D, Texture3D, CompressedTexture1D, etc.)

### ISSUE THREAD

**Issue by cgcostume** [cginternals/globjects#140]
while extending the texture header for compressed texture functions, i found the generalization into one texture class not well encapsulated.

A Texture is an OpenGL Object, but always a strictly specified Object in terms of its target/dimensions. So if there is no very good reason to 
1.) call `image1D()` on a `Texture` that is a 2D texture, 
2.) call `image#D(target, ..)` when target should be always identical with the texture dimensions?
i would suggest to introduce the following classes:
`Texture` as superclass for textures
`Texture1D`, `Texture2D`, `Texture3D`, `CompressedTexture1D`, `CompressedTexture2D`, `CompressedTexture3D`, `CubeMapTexture`, perhaps more... that only provide the interface that makes sense and do not lead to wrong enum errors. And not provide the functions with target property as method anymore.

Please discuss.

**Comment by scheibel** [comment]
I'm still not convinced such classes should be part of globjects.

I analysed the current implementation of ```Texture``` and indeed found some methods that are only valid in certain use-cases. Basically, it doesn't make any sense to call ```image3D``` on a 2D texture.

Further, the suggested list of classes (identified through descriptive texture types) would look like this when complete:
* GL_TEXTURE_1D
* GL_TEXTURE_1D_ARRAY
* GL_TEXTURE_2D
* GL_TEXTURE_2D_ARRAY
* GL_TEXTURE_3D
* GL_TEXTURE_4D_SGIS
* GL_TEXTURE_RECTANGLE
* GL_TEXTURE_CUBE_MAP
* GL_TEXTURE_CUBE_MAP_ARRAY
* GL_TEXTURE_BUFFER
* GL_TEXTURE_2D_MULTISAMPLE
* GL_TEXTURE_2D_MULTISAMPLE_ARRAY
* GL_TEXTURE_1D_STACK_MESAX
* GL_TEXTURE_2D_STACK_MESAX

And because of the orthogonal feature of proxy textures, this list is doubled:
* GL_PROXY_TEXTURE_1D
* GL_PROXY_TEXTURE_1D_ARRAY
* GL_PROXY_TEXTURE_2D
* GL_PROXY_TEXTURE_2D_ARRAY
* GL_PROXY_TEXTURE_3D
* GL_PROXY_TEXTURE_4D_SGIS
* GL_PROXY_TEXTURE_RECTANGLE
* GL_PROXY_TEXTURE_CUBE_MAP
* GL_PROXY_TEXTURE_CUBE_MAP_ARRAY
* GL_PROXY_TEXTURE_2D_MULTISAMPLE
* GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY
* GL_PROXY_TEXTURE_1D_STACK_MESAX
* GL_PROXY_TEXTURE_2D_STACK_MESAX

And compressed textures aren't even depicted using texture types but data types, which would increase the number of classes even more:
* GL_TEXTURE_1D_COMPRESSED
* GL_TEXTURE_1D_ARRAY_COMPRESSED
* GL_TEXTURE_2D_COMPRESSED
* GL_TEXTURE_2D_ARRAY_COMPRESSED
* GL_TEXTURE_3D_COMPRESSED
* ...

And with proxy textures...
* GL_PROXY_TEXTURE_1D_COMPRESSED
* GL_PROXY_TEXTURE_1D_ARRAY_COMPRESSED
* GL_PROXY_TEXTURE_2D_COMPRESSED
* GL_PROXY_TEXTURE_2D_ARRAY_COMPRESSED
* GL_PROXY_TEXTURE_3D_COMPRESSED
* ...

Together with the wish to store driver-known properties of a texture I would suggest moving this feature to gloperate, where we are able to reduce the specialized texture classes to those that are typically needed.

**Comment by acterhd** [comment]
I have own idea. I suggest unify: Texture2D with compressed and multisampled. 
Not use 4D (at this time). 
Make inheritance for every specialization
