### ISSUE TITLE
GLM is required to build but is not documented

### ISSUE THREAD

**Issue by DavidR91** [cginternals/globjects#322]
GLM is required to build but this is not currently listed as a prerequisite in the README

`find_package(GLM REQUIRED)`

```
CMake Error at /usr/local/Cellar/cmake/3.7.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):

  Could NOT find GLM (missing: GLM_INCLUDE_DIR)

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGLM.cmake:21 (find_package_handle_standard_args)
  source/globjects/CMakeLists.txt:6 (find_package)
```

**Comment by scheibel** [comment]
Thanks for the hint, it is now mentioned including required versions.
Current minimum should be 0.9.5, although the 0.9.4 branch may be working.
However, I'm hoping a current release of GLM is available on each system so that both globjects and using software may benefit from current GLM and its improvements and fixes.

**Comment by cgcostume** [comment]
seems fixed, @DavidR91 thanks for reporting.
